### ISSUE TITLE
HWND vs syscall.Handle in function declarations?

### ISSUE THREAD

**Issue by rodrigocfd** [JamesHovious/w32#19]
There's a definition for the type `HWND` in typedef.go, but it seems that many functions use `syscall.Handle` to type the `hwnd` parameter... for example, `GetWindowTextW` from user32.go.

Is there a reason for that?

**Comment by TotallyGamerJet** [comment]
I don't believe so. It should probably be fixed. Just cast so that it works: `syscall.Handle(hwnd)`
