### ISSUE TITLE
Need help with windows api data type

### ISSUE THREAD

**Issue by tejaskumark** [JamesHovious/w32#22]
@JamesHovious 
Hi James,
I stumbled across your repo, and it helped me a lot to understand wlanapi using into golang. Thanks for that.
I am reaching out to you for one of my query, I am trying to use winapi - https://docs.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlansetprofileeapxmluserdata, and I am quite a bit lost here.

As per description -

strProfileName
The name of the profile associated with the EAP user data. Profile names are case-sensitive. This string must be NULL-terminated.

strEapXmlUserData
A pointer to XML data used to set the user credentials.

Both of above having same type LPCWSTR, but one is direct string and another one is pointer. So I am not sure how to translate these two types to golang struct or may be I am missing something here.

So far I have tried with https://golang.org/pkg/syscall/?GOOS=windows#UTF16PtrFromString, but I am really lost as api is not throwing any error as well and it is not setting values as well.

Questions - 
- strProfileName How can I convert this go string to win api data type?
- strEapXmlUserData is going to be one on disc xml file. How can I parse this into golang(so that windows can understand xml data) and convert this to win api data type?

Any pointer in right direction is appreciated.

Thanks in advance.

**Comment by JamesHovious** [comment]
I’ll try and check this out over the next week or so and let you know what I come up with :)

**Comment by tejaskumark** [comment]
@JamesHovious I have figured it out and it looks like documentation mistake. Thank you for your help.
