### ISSUE TITLE
Why is gcc needed?

### ISSUE THREAD

**Issue by David263** [JamesHovious/w32#27]
The ReadMe says to get gcc, but doesn't explain why. Isn't Go by itself powerful enough to call C++ functions in the win32 dlls? Or is marshalling of arguments (ugh) necessary or something similar? I want to use Go all by itself to create a tiny REST server that can create and handle messages for a Windows window, as the basis for general app programming in Windows. Am I deluded as to Go being used in this way?

**Comment by JamesHovious** [comment]
At the moment there are a few APIs that use CGO (for example `func SendInput(inputs []INPUT)`) however this requirement should be removed in the future
