### ISSUE TITLE
Request to add a new version tag

### ISSUE THREAD

**Issue by zvodd** [JamesHovious/w32#31]
This latest version of this repositry with a valid go version tag "v1.1.0" seems to be a commit from 2017. At least from what I can tell.

Having recently pulled the lastest commit into a project using ` go get -u github.com/JamesHovious/w32@**commithash**` , which seems to work. It seems reasonable to create a new version tag, so we can get recent versions of the repo with the less specfic `go get -u github.com/JamesHovious/w32` or have it auto added by editor tooling after adding an import statement.

I'm not sure what a sutiable version number would be, maybe v1.2.0

The git commands to push a new tag would be :
```
git commit --allow-empty
git tag v1.2.0
git push origin v1.2.0
```

**Comment by JamesHovious** [comment]
Good call!, `v1.2.0` has been released.
