### ISSUE TITLE
Cgo

### ISSUE THREAD

**Issue by pjebs** [JamesHovious/w32#34]
Does this require cgo?

**Comment by zvodd** [comment]
No the w32 module dynamically loads windows `dll` (Dynamicly Loaded Libraries) files with `syscall.NewLazyDLL()`. The syscall gets the OS to add the executable into your go app's runtime memory.

`syscall.LazyDLL.NewProc()` calls `syscall.LazyDLL.LazyProc.Find()` which finds a pointer in memory to the exported functions, by name, in the DLL... and (I assume) some go runtime magic ends up making the correct style of [call](https://en.wikipedia.org/wiki/X86_calling_conventions) to run the function when `syscall.Proc.Call` happens.
